# Generated by Django 3.2.6 on 2021-08-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruiterApp', '0004_rename_username_recruiter_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='email',
            new_name='username',
        ),
    ]
